### ISSUE TITLE
Review walkthroughs and list all datasets needed for the package

### ISSUE THREAD

**Issue by restrellado** [data-edu/data-science-in-education#119]

**Comment by restrellado** [comment]
Waiting on author input about more datasets that needed to be loaded into `dataedu`

**Comment by jrosen48** [comment]
I see the following being available in dataedu:

```{r}
c("apaTables", "dummies", "ggraph", "here", "janitor", "lme4", "lubridate", "performance", "readxl", "rtweet", "randomNames", "sjPlot", "tidygraph", "tidyverse", "tidytext")
```

Some to possibly add:

- caret
- ggraph
- randomNames
- tidylog

**Comment by ivelasq** [comment]
added caret and tidylog to the package! ggraph and randomNames were already on there :)

**Comment by restrellado** [comment]
Just checking in on this–any other datasets that need to be pulled into the package? I'll wait a bit more and if there's nothing else I'll close it

**Comment by ivelasq** [comment]
I don't think all of the datasets are in the package yet. I can verify and share.

**Comment by restrellado** [comment]
Just leaving a friendly reminder to chime in with any datasets that need to be added to the package and if you need any support getting them in @jmostipak @jrosen48 @ivelasq @emilybovee

**Comment by restrellado** [comment]
All done
