### ISSUE TITLE
Include instructions for installing devtools and dataedu packages to the foundational skills chapter

### ISSUE THREAD

**Issue by restrellado** [data-edu/data-science-in-education#130]
We need some instructions for using `devtools::install_github("data-edu/dataedu")`

**Comment by emilybovee** [comment]
Hey @restrellado this is the current text about the dataedu package from the text analysis walkthrough. I just opened a similar issue to this to make sure we've explained our package before we start using it.. but I can close that issue if you're planning on putting it in foundational skills (which I think is a good idea).

FROM TEXT ANALYSIS CH, CURRENT FIRST USE OF THE PKG
Just a reminder, if you haven't already installed the `dataedu` package, you can do so by typing this code: 

```{r install dataedu, eval=FALSE}
devtools::install_github("data-edu/dataedu")
