### ISSUE TITLE
Can't source theme_dataedu.R and palette_dataedu.R in 10a-walkthrough-6.Rmd

### ISSUE THREAD

**Issue by restrellado** [data-edu/data-science-in-education#131]
The RMarkdown file gets stuck when executing this  

`source("r/theme_dataedu.R")`
`source("r/palette_dataedu.R")`

I see this in the console and I type `y`
`Importing fonts may take a few minutes, depending on the number of fonts and the speed of the system. Continue? [y/n] y`

Then it returns this: 

`input string 4 is invalid in this localeinput string 4 is invalid in this localeinput string 4 is invalid in this localeinput string 4 is invalid in this locale`

**Comment by restrellado** [comment]
PS I'll set eval=FALSE on that code chunk for now until we fix it

**Comment by ivelasq** [comment]
Hi! I see the warning message too (for theme_dataedu, no issues with palette_dataedu). However, the function still loads. Does it load for you too?

**Comment by restrellado** [comment]
No, the code chunk that sources the R file just gets stuck trying to run. For reference, it's code chunk 1: load custom themes in 10a-walkthrough-6.Rmd

**Comment by restrellado** [comment]
Update on this. It looks like there's a prompt to download some fonts when you source `theme_dataedu.R`. Once I responded `y` to that it seems to run. Two more things to tackle on this: First,  I don't think the `dataedu` palettes are working on this. My graphs are still using the default `ggplot` colors. Second, I don't know if this is going to cause any problems with the bookdown render. I'll keep working on this.

**Comment by restrellado** [comment]
Fixed in #181
