### ISSUE TITLE
Typo in 06-walkthrough-1.Rmd

### ISSUE THREAD

**Issue by droza0** [data-edu/data-science-in-education#136]
This book is awesome. Found a typo in walkthrough 1: in the code chunk on lines 205-213: 

```{r}
# split course section into components
s12_course_data <- s12_course_data %>%
  separate(col = CourseSectionOrigId,
           into = c('subject', 'semester', 'section'),
           sep = '-',
           remove = FALSE)

```

`CourseSectionOrigId` should be `CourseSectionOrigID`, otherwise it's not found.

**Comment by restrellado** [comment]
Thank you so much for this! We were trying to figure out why that wasn't working
