### ISSUE TITLE
_07-wt-multilevel-models-2.Rmd: Can't find the dataset to read in

### ISSUE THREAD

**Issue by restrellado** [data-edu/data-science-in-education#158]
I think the path needs to be corrected to the dataset on this one. Once all the code runs we can change the file name and get it rendered in bookdown

**Comment by jrosen48** [comment]
I believe this is fixed - pushed the latest dataset directly to master. Filename still needs to be changed.

**Comment by restrellado** [comment]
Everything rendered in bookdown so should be good here
