### ISSUE TITLE
Connect datascienceineducation.com with our Netlify-hosted gitbook?

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#161]
At some point, we need to connect datascienceineducation.com with our Netlify-hosted gitbook. I think this would involve changing the nameservers to point to netlify - and then changing some Netlify setting to use our custom URL.

Seperately, would it make any sense to also purchase dsieur.com?

**Comment by ivelasq** [comment]
The URL is up! https://www.datascienceineducation.com/

**Comment by jrosen48** [comment]
sweet to the beat!
