### ISSUE TITLE
edit conclusion chapter?

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#162]
Should we add a conclusion chapter?

**Comment by jrosen48** [comment]
I added this in #166, but it could still use a good review. I'm wondering if we can (in particular) highlight some future directions (and maybe challenges) for the field here? not sure. We can also perhaps summarize some of the main points from the book?

**Comment by ivelasq** [comment]
There's a bit of overlap between the Learning More chapter and the Conclusion. I think we can move some of the Take on Challenges/turning to something else to the Learning More chapter. Maybe the Conclusion chapter can focus more on addressing things we brought up in the Intro?

Also, @joshuarosenberg can you check the references in the latest render at the bottom of the Conclusion chapter please? You can see this code:
`if (knitr::is_html_output()) ‘# References {c20}’`

**Comment by restrellado** [comment]
Closing this and referencing #324
