### ISSUE TITLE
Finalize acknowledgements

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#163]
Thinking about something for closer to submission - adding an acknowledgments section! Here is part of what can go in there (it's from [this post](https://joshuamrosenberg.com/posts/introducing-data-science-in-education-using-r-forthcoming-2020/):

> We started writing this book in the open, on GitHub, and, as a result, this work was supported by many individuals it the [Data Edu Slack channel](https://dataedu.slack.com/) in which this book took form. On behalf of my co-authors, thank you to everyone who contributed code, suggested changes, asked questions and filed issues, and even designed a logo for us: [Abi Aryan](http://www.abiaryan.com/), [Jason Becker](https://www.linkedin.com/in/jsonbecker/), [William Bork](http://www.williambork.com/), [Erin Grande](http://eringrand.github.io/), [Jake Kaupp](http://www.jakekaupp.com/), [Ludmila Janda](https://www.linkedin.com/in/ludmila-janda-866259119/), [Kris Stevens](https://www.linkedin.com/in/kristopherdelanestevens/), [David Ranzolin](https://github.com/daranzolin), and [Bret Staudt Willet](http://bretsw.com/). 

I'm sure we'll all want to add to this.

**Comment by jrosen48** [comment]
I'm sure we'll all want to add to this at some point.

**Comment by ivelasq** [comment]
Yeah maybe all the people who did interviews too?

**Comment by eringrand** [comment]
First, thank you for including me in your acknowledgments. Secondly, my last name doesn't end in an 'e'.   :)

**Comment by ivelasq** [comment]
Hi @joshuarosenberg - Chapter 0 has been added for the acknowledgements for you. I think we need to add interviewees, new people who have contributed, etc.
