### ISSUE TITLE
Add preface in which we tell our individual and collective origin stories?

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#164]
Wondering if we can add a preface in which we can tell our individual and collective origin stories - how we came to data sci/R and how this all took form.

**Comment by emilybovee** [comment]
Interested, good idea Josh - maybe it's a final-stretch task once the rest of the content is finalized?

**Comment by ivelasq** [comment]
Preface has been added (@restrellado 's Chicken Story :)) but collective stories still in other chapter.
