### ISSUE TITLE
Export plots per publisher specs

### ISSUE THREAD

**Issue by restrellado** [data-edu/data-science-in-education#165]
>Number them and put a callout in the text (e.g. [insert fig 1]. Preferably at at least 1500 pixels along the longest edge and 300 dpi

**Comment by jrosen48** [comment]
Wondering if there is a way to automatically do this... And place at the end of the text. If not documented in bookdown book, maybe something to reach out to folks about?

**Comment by restrellado** [comment]
We have a system for exporting the plots now so I'm closing. If anyone sees problems with individual plots, please submit an issue. Thanks!
