### ISSUE TITLE
mention the challenges (and benefits) of working with states/districts/schools/teachers in the challenges section?

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#167]
Wondering if we should mention the challenges (and benefits) of working with state departments of education, districts, schools, and teachers in [the challenges chapter](https://github.com/data-edu/data-science-in-education/blob/master/04-unique-challenges.Rmd). I have limited experience, but wonder about mentioning, for example, the importance of gaining trust from principals and teachers before trying to collect data. I wonder if similar principles exist for the "higher" levels of states and districts - and if others have ideas for strategies/how to mitigate these challenges.

**Comment by restrellado** [comment]
Sounds like discussion on this has slowed down so I'm going to close it for now. But feel free to reopen when needed.
