### ISSUE TITLE
Format headings according to T&F spec

### ISSUE THREAD

**Issue by restrellado** [data-edu/data-science-in-education#182]
From T&F: 

Headings

We prefer the use of Word styles to indicate different levels of headings.

If you cannot use Word styles, please ensure that you present headings consistently with different levels of headings clearly differentiated. For example, use bold for level 1 subheadings,
italics for level 2 subheadings, and roman for level 3 subheadings, i.e.:

# Subheading level 1
*Subheading level 2*
Subheading level 3

**Comment by ivelasq** [comment]
Thanks Ryan! Maybe we can do this with CSS...? Will look into it.

**Comment by jrosen48** [comment]
*possibly* relevant - using a `.docx` template: https://rmarkdown.rstudio.com/articles_docx.html

**Comment by jrosen48** [comment]
in case we go down the reference doc route, here's what I've done in the context of my CV:

- Included in [my `.Rmd` document](https://github.com/jrosen48/utk-homepage/blob/master/about-source.Rmd this output YAML:

```{YAML}
output:
  word_document:
    reference_docx: Rosenberg-CV-template.docx
```

- Created [my Word document template](https://github.com/jrosen48/utk-homepage/blob/master/static/cv/Rosenberg-CV-template.docx), by setting the Word styles in the way described in [this article](https://rmarkdown.rstudio.com/articles_docx.html)

- Running the following to render:

`rmarkdown::render("static/cv/rosenberg-cv-for-word.Rmd", output_format = "word_document")`

**Comment by restrellado** [comment]
Headings are all consistent now
