### ISSUE TITLE
Organize bibliography

### ISSUE THREAD

**Issue by restrellado** [data-edu/data-science-in-education#183]
@jrosen48 Fyi there's a spec for the bibliography in the T&F author guidelines. Wasn't sure if you've seen that yet?

**Comment by jrosen48** [comment]
checking

**Comment by jrosen48** [comment]
Here are the guidelines w/ some notes

> The reference list/bibliography for each chapter should be placed at the end of each chapter.
Avoid providing a single reference list/bibliography at the back of the book unless appropriate
to your discipline. This will give readers the additional option of accessing your book by chapter.

I'm inclined to end of the book (and I think this is more common); I think references by chapter would be more common for an edited book. Though [it is possible to do this](https://stackoverflow.com/questions/45028623/is-there-a-way-to-add-chapter-bibliographies-using-bookdown) if we want. Perhaps something to ask Hannah about.

> Ensure that your references are consistently presented in terms of: the order in which details
are listed; use of capitalization; use of italics and punctuation.

Will do.

> Book and journal titles should always be in italics, regardless of which style guide you are
following.

Will do.

> Ensure that each entry includes all publication details as applicable: author/editor name(s) and
initials; date of publication; book or article title; journal title and volume number; place of
publication; publisher; page numbers for chapter or journal articles.

Will do. 

> Please include DOIs (Digital Object Identifiers) for all publications you reference (including
books) where available, this guarantees that others will be able to easily locate and access
your listed references.

Will do, perhaps after an initial pass through.

> It is essential that the reference list/bibliography includes every work cited by you in the text.

OK. 

> Please do not include search engine or database search URLs (e.g. EBSCO, Google, etc.).

OK.

> Please ensure you check that the date for each entry in the reference list/bibliography
matches the date cited in the text reference. This will avoid time-consuming queries at copyediting stage.

Noting this.

**Comment by jrosen48** [comment]
> There are different style preferences for different subject areas, such as Chicago or APA. Your
Editorial Assistant will advise which style you should follow.

Confirm APA?

**Comment by jrosen48** [comment]
I think these are mostly on the right track, but leaving this open. Going to close #196, as that only contained this related issue:

> One question I have has to do with how certain kinds of citations will render; it may take another iteration to get them behaving correctly, especially for those where the text is something like “Author’s (2019)” book, Data Science in Education)” - I think the apostrophe may not have ended up in the correct place (based on how I did it).

**Comment by ivelasq** [comment]
Not sure if this belongs under this issue, but there are chapters where the references are not in the book.bib file (example: Chapter 10 under Tidy the dataset).

**Comment by jrosen48** [comment]
Wondering if there's a way to tell bookdown that we want the references to be rendered in APA format. That would help to address a number of these requirements at once.

There is something in the bookdown book on this, but it seems to suggest it only applies to the PDF output:

```{}
Once you have one or multiple .bib files, you may use the field bibliography in the YAML metadata of your first R Markdown document (which is typically index.Rmd), and you can also specify the bibliography style via biblio-style (this only applies to PDF output), e.g.,
---
bibliography: ["one.bib", "another.bib", "yet-another.bib"]
biblio-style: "apalike"
link-citations: true
---
```{}

**Comment by ivelasq** [comment]
ahh, I think I  made a mistake in the index.Rmd file in that it's not in quotes!

**Comment by ivelasq** [comment]
https://github.com/data-edu/data-science-in-education/blob/master/index.Rmd

**Comment by ivelasq** [comment]
please feel free to fix and I will rerender.

**Comment by jrosen48** [comment]
sweet to the beat, will do

**Comment by ivelasq** [comment]
Added the apa_pl.csl file and pandoc args to _output.yml and rerendered - looks like APA format now!
