### ISSUE TITLE
request for help annotating c17-additional-resources

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#195]
This came from #186 - I added brief (less than one sentence) annotations to the references in [c17-additional-resources](https://github.com/data-edu/data-science-in-education/blob/master/17-additional-resources.Rmd) - but, wasn't familiar with some of the cites, and so am requesting help (and need to skim a few myself to be able to summarize).

**Comment by duttashi** [comment]
@jrosen48 , @restrellado I would like to take this issue up. However, the embedded url pointing `c17-additional-resources` is broken. It gives me a "Page not found error".

**Comment by jrosen48** [comment]
@duttashi thanks so much! We reordered the chapters and it is now chapter 18 [here](https://github.com/data-edu/data-science-in-education/blob/master/18-additional-resources.Rmd)

**Comment by restrellado** [comment]
@jrosen48 Just checking in. Did you get what you needed on this? Anything I can do to help?

**Comment by jrosen48** [comment]
Thanks - (we) still need to elaborate on some of the resources (i.e., to describe Peng's book - there's a placeholder for the description). Woudl appreciate help but I can also work to chip away at this.

**Comment by restrellado** [comment]
@jrosen48 and I are working on this one today. Adding as many descriptions as we can, then doing general tidying up
