### ISSUE TITLE
Data: plural or singular?

### ISSUE THREAD

**Issue by ivelasq** [data-edu/data-science-in-education#20]
Sometimes "data" is plural and sometimes it is singular - can we norm on one?

**Comment by restrellado** [comment]
Yes! And thank you for the good catch. I found this [write-up](http://www.onlinegrammar.com.au/top-10-grammar-myths-data-is-plural-so-must-take-a-plural-verb/) useful. I'll have to go through the drafts more thoroughly, but I'm guessing that we're mostly using "data" to describe general information. In that case we should be using the singular. Open to other thoughts!

**Comment by restrellado** [comment]
Closing this one for now, but we can do a future copyediting issue to correct any inconsistencies with pluralization.
