### ISSUE TITLE
Need role descriptions 

### ISSUE THREAD

**Issue by restrellado** [data-edu/data-science-in-education#206]
cc: @ivelasq and @emilybovee

**Comment by emilybovee** [comment]
I updated my role description, ready for you @ivelasq !

**Comment by restrellado** [comment]
Thanks @emilybovee ! Will you be doing an update in a PR?

**Comment by emilybovee** [comment]
I did, but merged it right away yesterday morning. Should be in master now!

**Comment by ivelasq** [comment]
Done!

**Comment by restrellado** [comment]
Awesome thanks all!
