### ISSUE TITLE
Make sure that the description of dataedu package comes with the first mention of the package

### ISSUE THREAD

**Issue by emilybovee** [data-edu/data-science-in-education#208]
This will depend on final positioning of walkthroughs. Current description of package from Text Analysis ch...

Just a reminder, if you haven't already installed the `dataedu` package, you can do so by typing this code: 

```{r install dataedu, eval=FALSE}
devtools::install_github("data-edu/dataedu")

**Comment by restrellado** [comment]
Thanks for this @emilybovee ! The instructions should be going in the foundational skills chapter. I'll close this one since its referenced in #130
