### ISSUE TITLE
publicly available data

### ISSUE THREAD

**Issue by ivelasq** [data-edu/data-science-in-education#21]
Hi again,

I can most contribute on topics regarding wrangling public datasets. I've worked with NAEP and would be glad to take on that chapter. Another thing I was thinking was showing imputation with [EdFacts](https://www2.ed.gov/rschstat/landing.jhtml?src=pn) graduation data, which is suppressed when there are small cell sizes. Let me know if this is applicable to your work and how I can get started!

**Comment by jrosen48** [comment]
Isabella, I think this sounds like a fantastic addition to this project! Thanks for considering contributing (and sharing your expertise). Okay, two ideas for thought:

1. Could the imputation with EdFacts data be a section of Advanced Uses (preview: multi-level models [i.e., HLM], network analysis, and text analysis are presently part of the section).

2. I'm thinking NAEP data could be a *great* walkthrough. I'd like to hear your and others' thoughts, but I'm continually curious about how to approach these datasets; I think others (those working in schools/districts, for organizations like Gates Foundation, and researchers in universities) would be, too.

Hope these make sense. Thanks again--looking forward to the opportunity to work on this book with you!

**Comment by jrosen48** [comment]
Isabella, just wanted to circle back to this - continue to think these are important contributions and hope that you'd still be interested in contributing (if interested, we have next convo sched. for Tuesday, August 7, at 9:00 pm EST; could definitely discuss then, too).

**Comment by kierisi** [comment]
I'm happy to start working on walkthroughs with the NAEP data.

**Comment by jmostipak** [comment]
in thinking about K-12 educators and what they're most likely to be familiar/working with, I came back to gradebooks. they're a mess, and there's *a lot* to unpack in terms of getting them into a tidy format, but I also think it's the most accessible/relatable data for educators to be working with.

I've gone ahead and started working on a gradebook walk-through for walkthrough #2 and will get a PR with my (limited) progress out shortly!

**Comment by restrellado** [comment]
Hey y'all! Just wanted to get this conversation going again. I see that Jesse started working on the gradebook walkthrough. Do we still plan to do a walkthrough using NAEP data? If so, I'm happy to open up another file as a placeholder.

**Comment by ivelasq** [comment]
Yup! NAEP will be Walkthrough 5: https://github.com/data-edu/data-science-in-education/blob/master/10-walkthrough-5.Rmd

**Comment by restrellado** [comment]
Awesome! I'll close this down then open up new issues for the gradebook chapter and the NAEP chapter and will assign Jesse and Isabella respectively. Thanks!
