### ISSUE TITLE
Need an introduction to ggplot

### ISSUE THREAD

**Issue by restrellado** [data-edu/data-science-in-education#234]
The first reference to ggplot is right around line 473 of the multi-models chapter

**Comment by kierisi** [comment]
there's a brief intro in the gradebook - chapter 8 - that could be built out. I could also see reworking this chapter a bit to focus more on wrangling//tidying data and ggplot.

**Comment by restrellado** [comment]
Addressing this in #262

**Comment by jrosen48** [comment]
Thanks @restrellado for addressing this
