### ISSUE TITLE
Create a style guide

### ISSUE THREAD

**Issue by restrellado** [data-edu/data-science-in-education#25]
This was an idea we discussed during our call on August 7, 2018. The idea was to create a style guide to make our code consistent. We should also use the style guide to select one package when there are multiple packages that have similar purposes.

**Comment by kierisi** [comment]
are there any objections to the `tidyverse`? I'll argue that it provides consistent syntax and formatting that is also easy to read, and consistent between packages.

I realize this may require re-writing some chapters, and is a pretty heavy enforcement of style. however if the audience is largely coming from a non-technical background and looking to develop their skills in data science, the benefits of using the tidyverse are numerous.

**Comment by jrosen48** [comment]
I think adhering to the tidyverse is a great idea.

**Comment by restrellado** [comment]
I live in tidyverse. I'm all for it!
