### ISSUE TITLE
Controlling for `course_id` drops `course_id` levels in the model output

### ISSUE THREAD

**Issue by restrellado** [data-edu/data-science-in-education#264]
This happens at line 142 of `13-wt-multilevel-models.Rmd`. The output from this model should include 25 `course_id` levels and one dummy variable: 

```
lm(percentage_earned ~ TimeSpent_std + course_id, data = dat) %>% summary()
```

but I only see 20 `course_id` levels and one dummy variable. We can verify that there are actually 26 `course_id` levels like this: 

```
dat %>% 
  count(course_id) %>% 
  nrow()
```

and if we fit a model for course IDs on time spent in the course, we get the expected number of course IDs–25 plus one dummy variable: 

```
lm(percentage_earned ~ TimeSpent_std, data = dat) %>% summary()
```

Somehow controlling for `course_id` drops levels, but `course_id` as the only independent variable keeps all levels. 

cc: @jrosen48

**Comment by jrosen48** [comment]
The second `lm()` call i supposed to be the following, correct?

```{r}
lm(percentage_earned ~ course_id, data = dat) %>% summary()
```

**Comment by restrellado** [comment]
Yes that's correct–sorry for the typo!

> The second `lm()` call is supposed to be the following, correct?
> 
> ```
> lm(percentage_earned ~ course_id, data = dat) %>% summary()
> ```

**Comment by jrosen48** [comment]
De na - and, just to confirm - sorry - these are still dropped with that call?

**Comment by jrosen48** [comment]
k, sorry, checking

**Comment by restrellado** [comment]
> De na - and, just to confirm - sorry - these are still dropped with that call?

We figured it out in Slack but I'll put here also, just for the record. The `course_id` variable needs to be changed in the dataset before we can confirm the levels still get dropped using `lm(percentage_earned ~ course_id, data = dat) %>% summary()`

**Comment by restrellado** [comment]
Everything works now! The correct variables are in the current version of {dataedu} so I just needed to update it for the correct number of levels in `course_id` to appear in the model output. 

So friendly reminder to readers to make sure and update {dataedu} regularly by using `devtools::install_github("data-edu/dataedu")`
