### ISSUE TITLE
inconclusive self-rating system in chapter 2

### ISSUE THREAD

**Issue by kierisi** [data-edu/data-science-in-education#280]
in chapter 2 we ask readers to rate themselves on a scale from 1 to 5 on:

- Using R
- Education as a field
- Statistics

but then only provide guidance based on what they rate themselves in using R. would it be helpful to address both education as a field as well as statistics?

**Comment by jrosen48** [comment]
Yes, concur - I really like the idea of pointing to resources to help folks feel more comfortable with one of these domains.

**Comment by restrellado** [comment]
Yep makes sense to do this. Thanks Jesse!
