### ISSUE TITLE
Review all visualizations and theme with DSIEUR theme

### ISSUE THREAD

**Issue by restrellado** [data-edu/data-science-in-education#293]

**Comment by ivelasq** [comment]
Can you remind me what we're looking for? I think we should wait until the font for the graphics is decided, then I can remove {extrafont} and just have the font we want.

**Comment by restrellado** [comment]
No problem I'm good with that! The idea for this issue was to go through all the chapters looking for code chunks that make plots, then double checking to make sure the plots used the DSIEUR theme. If that's done already, I'm good with closing this

**Comment by ivelasq** [comment]
Ahh okay! Good call :) I haven't gone through to make sure the theme is on everything - let's leave this open for now.

**Comment by ivelasq** [comment]
New code for theme! I already see it didn't fully work on some chapters (like walkthrough 3) though...

**Comment by ivelasq** [comment]
I think I know how to fix this... + theme_dataedu() has to be the last thing on the plot (don't know why). Will fix.
