### ISSUE TITLE
Add instructions for responding to prompts after running code

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#304]
If you have not run this before:

```{r}
tidytext::get_sentiments("nrc")
```

When rendering the book, it seems like you can't select `1` to allow the download to proceed programmatically. Is there any way to do this programmatically? Or, otherwise, tell folks they have to do this before rendering?

**Comment by restrellado** [comment]
Yep it's in there. I chose to explain it rather than make it automatic, but I'm open to changing that if needed: 

>To explore this dataset more, we'll use a {tidytext} function called `get_sentiments()` to view some words and their associated sentiment. If this is your first time using the NRC Word-Emotion Association Lexicon in the {tidytext} package, you'll be prompted to download the NRC lexicon. Respond "yes" to the prompt and the NRC lexicon will download. Note that you'll only have to do this the first time you use the NRC lexicon.

**Comment by jrosen48** [comment]
Thank you for pointing me to that. Sounds good, I think/agree this is good. Perhaps we can include this and any other steps that would need to be taken to render the book (in addition to using the function to mass install packages)? Not sure if there are any others...

**Comment by restrellado** [comment]
More info. Add similar language to 
 - {ggplot} code that requires prompts to use the dataedu theme  
 - The initial use of the dataedu packages mass install

**Comment by ivelasq** [comment]
@restrellado just a heads up that mass_install() is now install_dataedu() in case you reference that specifically.
