### ISSUE TITLE
Move Who we Are and What We Do to prologue?

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#310]
Right now, there is a (great) section of c3, *Who we Are and What We Do*. 

Should we move this to a prologue chapter?

https://github.com/data-edu/data-science-in-education/blob/f02d09f353ca8df58ce781d45eb45fb9b518a4db/03-data-scientist-in-edu.Rmd#L61

Minor, @kierisi, I imagine you may want to update your role - is this the case? Just mentioning this here after reading through it

**Comment by jrosen48** [comment]
@restrellado may I tag you in on this one, too?

**Comment by emilybovee** [comment]
I think moving this to the prologue sounds good; lmk if you guys want me to work on this

**Comment by restrellado** [comment]
Go for it @emilybovee ! I’ve been working on the conclusion so I haven’t gotten to this yet.

**Comment by ivelasq** [comment]
I like it in its current chapter because it's a sort of continuation of 'what data science in education' looks like - but understand if overruled!
