### ISSUE TITLE
Move Next Steps for Data Science in Education to c17 (Learning More)?

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#311]
Should we move the section in c3 *Move Next Steps for Data Science in Education* to [c17 (Learning More)](https://github.com/data-edu/data-science-in-education/blob/master/17-learning-more.Rmd)?

https://github.com/data-edu/data-science-in-education/blob/f02d09f353ca8df58ce781d45eb45fb9b518a4db/03-data-scientist-in-edu.Rmd#L93

**Comment by jrosen48** [comment]
@restrellado may I tag you in on this?

**Comment by restrellado** [comment]
Got it thank you Josh! I'll have a look
