### ISSUE TITLE
Adding over-arching sections to the book?

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#312]
Wondering what everyong thinks of sections (not sure how we'd do this technically)? Section 1: beginning through foundational skills. Section 2: foundational skills, possibly the first two or three walkthroughs. Section 3: more advanced/special-purpose topics. Section 4: learning more, working in an organization, conclusion. I imagine no more than 300-400 words to introduce each.

**Comment by ivelasq** [comment]
We can do it on bookdown - not sure about the actual book, though.

**Comment by ivelasq** [comment]
Well, the section heads on bookdown. Don't know about the section intros.

**Comment by ivelasq** [comment]
We could introduce them in 1.2 Making the Path a Little Clearer?

**Comment by ivelasq** [comment]
Regardless of what we do, we should make sure it's all consistent...

**Comment by jrosen48** [comment]
I like the idea of introducing them in 1.2. Then, perhaps we can give a brief (1 para or less) description in the first chapter for each section (maybe even just a sentence or two: "Here, in the first walkthrough, we show how to go about approaching a particular educational problem, like we do in all of the walkthroughs"). 

Agree about making sure it's consistent; thanks  for pointing that out.

**Comment by restrellado** [comment]
I'm open, but keep me posted on what we decide to do here. I'm working on the conclusion and trying to tie it back to what we talked about in the introduction

**Comment by emilybovee** [comment]
I'm open to this as well, but I don't see the book as sorting itself clearly into sections. At least not sections I could name. Are we thinking of doing generic names like "Getting Started," "Learning More," stuff like that? I'm not sure I see the value in sections if there aren't clear delineations as to what goes in what section (but still open to this).

**Comment by jrosen48** [comment]
@emilybovee what if they were very general, i.e.:

*Section 1*: beginning of the book through the first foundational skill chapter. This would mostly be "conceptual" content
*Section 2*: foundational skills #1 and #2, and perhaps some of the first few walkthroughs (though, I see your point here, that these can be hard to divide into "beginning" and "advanced" content, and I'd be okay with this section including *all* the walkthroughs)
*Section 3*: more advanced walkthroughs (unless Section 2 includes those)
*Section 4*: all of the content after the last walkthrough
