### ISSUE TITLE
Thoughts on separating foundational skills #2 into two chapters?

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#314]
Hi all, @kierisi and I have been discussing separating foundational skills #2 (titled [Foundational Skills](https://datascienceineducation.com/c06.html) into two chapters. We think this aligns with our broader goal of having two "tracks" for folks to get started: 

- One (a new foundational skills #2: up and running) for sort of everything to get up and running
- One (foundational skills #3: tidyverse) that is more tidyverse-focused)? 

Lastly, and relatedly, foundational skills #1 ([Getting Started With R and RStudio](https://datascienceineducation.com/c05.html) can (still) be about getting started. Some of the content from the suggested new foundational skills #2 chapter could potentially be moved to this (foundational skills #1 chapter).

Another option would be to move a *lot* of what is in now-foundational skills #2 into foundational skills #1. I and I think we are definetly open to this, though it seems like a bit of imposition into the content of this chapter and its aims. Also, I like the idea of three foundational skills chapters :) 

Thoughts on this?

**Comment by jrosen48** [comment]
Here's how sub-sections could possibly be separated into possible new chapters:

**Foundational Skills #1 - Started Out**

- Overview
- Downloading R and RStudio
- Getting to Know R through RStudio
- Customizing Your RStudio Environment
- Exploring R Quickly With `swirl` (presently in foundational skills 2)
- Downloading and Accessing the Datasets Used in This Book (I think this needs to be created)
- Introduction to Help Documentation (presently in foundational skills 2)

**Foundational Skills #2 - Up and Running**

- Foundational Skills Framework
- Code for Foundational Skills
- Packages and Functions
- Installing and Loading a Package
- Reading Code and Writing Functions
- The Pipe Operator
- Functions and Equality (discussed in Slack a little while back possibly adding some of the other logical operators; unless we added this elsewhere in the book in the context of `filter()`ing? 
- Basics of Names

**Foundational Skills #3 - The tidyverse

- Using Functions to Import Data (moved from foundational skills 2; combine when possible with Loading Data from Excel, SAV, and Google Sheets (and from the web) at the end of the same chapter, otherwise ditch content from Loading Data from Excel, SAV, and Google Sheets)
- Processing Data (needs to be expanded, or cut)
- Communicating/Sharing Results (either needs to be cut or expanded, especially as we state elsewhere that R Markdown is out of the scope of the book)

Now that I walk through this, and look at what is in [chapter 7/walkthrough 1](https://datascienceineducation.com/c07.html) I am less certain of the need to add a third fondational skills chapter. Perhaps the Loading Data from Excel, SAV, and Google Sheets (and from the web) content could be integrated into the Using Functions to Import Data section in foundational skills 2, and the processing data and communicating/sharing results. 

Sorry for the long post!

**Comment by ivelasq** [comment]
another thought I had as I was reading through was breaking up Foundational Skills 2 into (1) chapter with overview of functions, packages, etc. and (2) the walkthroughs provided in FS2, like downloading dataedu and looking at the MA data.

not super relevant to this, but maybe we can move the dataedu reference in Foundational Skills 1 to the other Foundational Skills chapters?

**Comment by jrosen48** [comment]
like this. @kierisi and I just started to discuss something similar to this. thinking we will keep this the same until after some last edits to these chapters, after which it may be easy to see how all the pieces can fit together.
