### ISSUE TITLE
Kudos for 2.1.1

### ISSUE THREAD

**Issue by nkenner** [data-edu/data-science-in-education#317]
Josh asked me to proof through the book, and I particularly like 2.1.1's description of R learning. 100% describes code learning and language learning. Nail on the head.

Should be included as a preface and reminder in _all_ language classes

**Comment by jrosen48** [comment]
h/t to, I believe, @restrellado on this

also, thanks so much for proofing this!

**Comment by restrellado** [comment]
Thank you so much for reviewing this!

**Comment by emilybovee** [comment]
Yes @nkenner - thanks! We really appreciate it!
