### ISSUE TITLE
how will folks access and run the code for walkthroughs?

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#319]
minor, but how will folks access and run the code for walkthroughs; will we link to the `.Rmd` files, include the (extracted) code in {dataedu}, or something else?

Related, this is in foundational skills 2, and probably can be cut, but it may be good to keep this if we want to communicate to folks (maybe in chapter 2, how to use) how to run the walkthrough code:

```{r}
## Communicating / Sharing Results

R Markdown is a highly convenient way to communicate and share results. Navigate to "New File" and then "R Markdown".

Then, click "Knit to PDF", "Knit to HTML", or "Knit to Word".
```

**Comment by jrosen48** [comment]
tagging in @ivelasq

**Comment by ivelasq** [comment]
I think the current plan is to have the .R script with the code from the walkthroughs available in the package, but no plans for the .Rmd to be in there... I'll send a message out!

**Comment by emilybovee** [comment]
Yes I think that was the plan!
