### ISSUE TITLE
Finalize conclusion chapter

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#324]
> I think it reads reasonably well as a first effort but as always I’m looking forward to seeing how we can improve it. @Emily Bovee I tagged you for a review. You’ve been editing the other chapters so I think you’re in a good position to see how well the draft ties things up (from @restrellado)

**Comment by ivelasq** [comment]
Thanks so much for the new conclusions chapter! My thoughts is that it is similar to Chapter 17, Learning More. https://datascienceineducation.com/c17.html

Maybe we can merge and just keep one? Or differentiate them more?

**Comment by restrellado** [comment]
Note more background in #162

**Comment by jrosen48** [comment]
@restrellado finished this

**Comment by jrosen48** [comment]
in #323
