### ISSUE TITLE
Hyperlinks in bookdown: adding URL for book

### ISSUE THREAD

**Issue by ivelasq** [data-edu/data-science-in-education#326]
We have a lot of hyperlinks in the bookdown that don't have a URL that is visible. This is ok for the online version but book readers will have sentences like "to find this package click here." I think all hyperlinks need to include the URLs.

**Comment by jrosen48** [comment]
agree

**Comment by jrosen48** [comment]
if the link is really awful (like, many lines long), perhaps we can include as a footnote - but otherwise should put in parentheses - do you concur?

**Comment by ivelasq** [comment]
I think it's ok if there are hyperlinks that don't show up in the book but without a reference to them (like "click link here") - everything would be in the references, yes?
