### ISSUE TITLE
incomplete sentences at end of chapter 12

### ISSUE THREAD

**Issue by ivelasq** [data-edu/data-science-in-education#327]
The last couple of paragraphs of Ch 12 have incomplete sentences. In addition, they reference links that won't be visible in the printed book.

> One type of model extends the logistic regression. It can be used for data that is not only 1's and 0's but also data that is normally distributed . It is the amen package available [here](https://cran.r-project.org/web/packages/amen/index.html).

> A particularly common one is an Exponential Random Graph Model, or an ERGM. An R package that makes estimating these easy is available [here](https://cran.r-project.org/web/packages/ergm/index.html). That R package, {ergm}, is part of a powerful and often-used collection of packages, including those for working with network data (data that can begin with an edgelist, but may need additional processing that is challenging to do with edgelist data), {statnet}. A link to the statnet packages is [here](https://statnet.org/).

**Comment by jrosen48** [comment]
assigned myself on this

**Comment by jrosen48** [comment]
This was addressed in #357
