### ISSUE TITLE
add conventions used in the book

### ISSUE THREAD

**Issue by ivelasq** [data-edu/data-science-in-education#329]
Similar to Hands On Programming Using R, I think we should list the conventions in the book early and in an easy-to-find section: https://rstudio-education.github.io/hopr/preface.html#conventions-used-in-this-book

I think it belongs at the beginning of Foundational Skills 2 but would love to know what others think.

**Comment by jrosen48** [comment]
Nice, I think that's a good spot, too. Tagging @jmostipak in on this for input. Could also go in Foundational Skills 1.
