### ISSUE TITLE
Thoughts on moving end of Chapter 10 to beginning of Chapter 9?

### ISSUE THREAD

**Issue by ivelasq** [data-edu/data-science-in-education#338]
@restrellado reading through - the end of Ch 10/Walkthrough 4 does a great job introducing aggregate data. Since Ch 9 is intro to aggregate data, thoughts of putting it in there instead? Specifically thinking of the paragraph beginning in "Before we discuss the benefits of aggregate data..." and moving it before 9.1.1.1.

**Comment by restrellado** [comment]
Yep I’ll take care of this one

**Comment by restrellado** [comment]
Let's work on this one as part of #354
