### ISSUE TITLE
Double check numbers in Walkthrough 14

### ISSUE THREAD

**Issue by ivelasq** [data-edu/data-science-in-education#340]
Seems like with the changes we've made, the narrative isn't matching up with the code results. I tried to catch what I could but don't have the context expertise - could you please review? @emilybovee @joshuarosenberg

**Comment by ivelasq** [comment]
Also it looks like the model was tuned twice?
(see line 282 and 305 in the R Markdown)

**Comment by ivelasq** [comment]
This might be lack of content expertise I referenced...

**Comment by ivelasq** [comment]
^ ^ never mind re: last two comments

**Comment by ivelasq** [comment]
Anyway, I do think the chapter could use your eyes - like I am not sure where the Rsquared of 0.97 mentioned at the end comes from. Thank you!!!

**Comment by jrosen48** [comment]
@emilybovee may I ask if you could take a look at this? Wondering if this is due to when we temporarily had the wrong data (that made the fit look better than it ought to). Thank you for considering... and my sincere apologies for that issue, again.

**Comment by emilybovee** [comment]
closing because we have finally triumphed @jrosen48 @ivelasq
