### ISSUE TITLE
Missing citations in 16.2.5, 16.3.4, 17.4.2, 17.5.1

### ISSUE THREAD

**Issue by ramorel** [data-edu/data-science-in-education#345]
These citations are rendered as *???* in Bookdown. I corrected 16.3.4, 17.4.2, 17.5.1 (I think--I made them reflect the keys in the book.bib). Not sure about 16.2.5. The key looks right and the other instances of that key are rendered. 🤷‍♂️

**Comment by jrosen48** [comment]
Thanks so much @ramorel - will look into this!

**Comment by jrosen48** [comment]
Leaving this open to confirm that #346 and #347 both worked as intended upon next rendering of the book - thanks again @ramorel, our sincerest gratitude!
