### ISSUE TITLE
Ideas for chapter 10 (solutions for adopting data science techniques in education)

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#36]
Just a few ideas for this chapter--open to (and requiring) more ideas & input:

- Have a project/problem to work on 
- Start where people are (with the tools they use and the data they have - as well as the problems they are trying to solve with data science/R)
- Recognize that using data science tools such as R can take a long time and an investment of effort

**Comment by restrellado** [comment]
> Start where people are (with the tools they use and the data they have - as well as the problems they are trying to solve with data science/R)

Yes! I think one easy point of entry that doesn't require knowing R is working on generating and refining useful data science questions. I'd like to at least touch on this in this section for a couple reasons: First, it makes the point that folks who aren't ready to jump into programming and statistics can still participate in the analysis process. Second, if we apply statistics and programming without questions designed to benefit the overall educational system, we miss an opportunity to do data science in a way that is useful to a wider audience within school systems.

**Comment by restrellado** [comment]
Just clarifying the next action on this issue: write about content that informs part 3 of the narrative. 

I'll assign myself to this one but am happy to collaborate.

**Comment by restrellado** [comment]
We touched on this in the Solutions chapter. Closing for now, but can revisit if needed
