### ISSUE TITLE
[WIP] Erin's thoughts during read through

### ISSUE THREAD

**Issue by eringrand** [data-edu/data-science-in-education#361]
Using this issue as a place to put more general thoughts as I poke through the book.  I'm reading the version at https://datascienceineducation.com as of 3/13 so some of these things may be different than the codebase.

Foundational Skills: 
- image missing

Walkthrough 1: 
- Why sjPlot tab_model and not ggsummary?

Walkthrough 2: 
- Why `summary` instead of `skimr::skim`?

Walkthrough 4:
- identical(names(all_files[[1]]), names(all_files[[2]])) - haven' talked about subsetting yet, so this might be confusing

**Comment by jrosen48** [comment]
Thanks so much for these super helpful contributions. One question - can you remind me what pkg ggsummary is from? I like the sound of it (and dislike tab_model(), in part for reasons @ivelasq brought up - it's hard for us to automatically caption the output, as we'll need to do per #165 if we continue to use it the way we are)

**Comment by jrosen48** [comment]
Also, I'm a `skimr::skim` fan! If others okay with this, wondering if there are other cases when `skimr::skim` may be more informative (and which we should also change). @kierisi @ivelasq @restrellado @emilybovee

**Comment by jrosen48** [comment]
Last, re: Walkthrough 4... yeah. @emilybovee do you have any thoughts on this? I feel like you had brought up subsetting before (and the merits of using tidyverse approaches *when possible*). If not possible here, wondering if a brief intro. to subsetting is merited).

**Comment by jrosen48** [comment]
Ty so much, again, @eringrand, needless to say, these are super helpful as we get the book closer to ready to share with the world (and the publisher).

**Comment by eringrand** [comment]
Re. ggsummary, I got the name wrong, I was referring to the package {gtsummary}. More here - https://github.com/ddsjoberg/gtsummary

**Comment by jrosen48** [comment]
Got it, thanks. This looks promising.
