### ISSUE TITLE
Question about ideas for chapter 11 (students doing data science)

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#37]
This chapter is an odd duck: every other chapter focuses upon teachers/administrators/researchers/policymakers using data science techniques (and R), whereas this focuses more upon teaching individuals at the K-12 age.

I wonder if in some ways we can suggest that some of the ideas and techniques used in this book could be used to teach youth/students, i.e. some of the ideas potential ideas for chapter 10 discussed in #36. Thoughts?

In addition to possibly recapitulating (and adapting for younger R learners), some possible distinctions that may make this chapter different could be:

- K-12 students often need to meet standards
- There aren't stand-alone data science standards (though there are many elements in the science, math, and even computer science standards, i.e. modeling and information literacy)

**Comment by restrellado** [comment]
Good points! I think the original idea here was to argue for teaching K-12 students the "soft skills" relating to data science as a way to move the field forward. It goes back to the struggle we all have with creating a feeling of safety and confidence about how our data is used through transparency in methods and empathy for the consumers of the data. So if those principles get clarified and taught explicitly to younger folks, they end up working on the problems that evolve from that as opposed to the same problems we're struggling with. Let's keep on talking and writing through it and see how it takes shape.
