### ISSUE TITLE
What to do with chapter 6?

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#38]
Does anyone else find it sort of strange that Advanced Uses ([06-advanced-uses.Rmd](https://github.com/data-edu/data-science-in-education/blob/master/06-advanced-uses.Rmd)) comes before our walkthroughs? Can we move this--or integrate the content that would be in this into the walkthroughs?

**Comment by restrellado** [comment]
Totally open to moving this. Might be good to just go ahead and move it and see how it looks and reads as those sections take shape. Go ahead Josh!

**Comment by jrosen48** [comment]
will do, thx
