### ISSUE TITLE
wrap code chunks

### ISSUE THREAD

**Issue by ivelasq** [data-edu/data-science-in-education#383]
Thinking about the print book, we should wrap the text in code chunks so that you can read everything. Any idea how many characters to wrap it at?

I can get to this once I finish the images/tables for the manuscript unless someone has capacity now! :)

**Comment by jrosen48** [comment]
I have been working on this for the chapters I've been reading for narrative.

these may be useful?

I use this: https://github.com/tjmahr/WrapRmd

This looks useful: https://rdrr.io/cran/knitr/man/wrap_rmd.html

**Comment by jrosen48** [comment]
I can work on this if okay. Do you have experience using the knitr function?

**Comment by jrosen48** [comment]
made this post manuscript
