### ISSUE TITLE
package references no longer linked?

### ISSUE THREAD

**Issue by ivelasq** [data-edu/data-science-in-education#387]
Hi @joshuarosenberg - wanted to put this on your radar, all the package references are no longer linking. I wonder if something got lost in the git shuffle. Could you please take a look?

**Comment by jrosen48** [comment]
on it! 

Not to be conspiratorial, but I swear this has happened multiple times before!!! I can't figure it out, but will at the least create again in a PR.

**Comment by jrosen48** [comment]
is it possible bookdown is creating a `.packages.bib` file that is over-writing the one we're manually creating? hmmmmm

**Comment by ivelasq** [comment]
Perhaps... check out the introduction.Rmd file, it says:
`bibliography: [book.bib, packages.bib]`
Should we move it?

**Comment by jrosen48** [comment]
If #388, then perhaps we can make some changes to that. I think I I had manually added `packages.bib` to that value - I think before it was only `bibliography: book.bib` (or `bibliography: [book.bib]).
