### ISSUE TITLE
remove headings 4+

### ISSUE THREAD

**Issue by ivelasq** [data-edu/data-science-in-education#390]
Per the manuscript, we shouldn't have headings above 3. We could do a quick sweep. Maybe transform them to **bold**?

**Comment by jrosen48** [comment]
Tagging myself in here

**Comment by jrosen48** [comment]
@emilybovee tagging you in here per #398

**Comment by emilybovee** [comment]
Adding Josh's note to clarify the task here, per closed issue #398 
I didn't do this for c6, as there is an open PR for it (#375). Tagging in @emilybovee - when you review that chapter, can you change level-4 headers into bold text? We can leave #390 open until we finish that review.

**Comment by emilybovee** [comment]
Fixed in PR #429
