### ISSUE TITLE
fix simulated data for walkthrough 4

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#41]
For walkthrough 4 ([`09-walkthrough-4.Rmd`](https://github.com/data-edu/data-science-in-education/blob/master/09-walkthrough-4.Rmd)), there is a problem with the simulated data. The key when generating the data is that nominators with higher values of `yvar2` need to have relations with - have nominated - nominees with higher levels of `yvar1`. This isn't the case yet.

**Comment by jrosen48** [comment]
Just as a bit of context, this walkthrough involves an expansion of [a blog post I wrote](https://joshuamrosenberg.com/blog/social-network-analysis-model-for-influence/); there, I used a very small data set (*n* = 6!). I hoped this example would involve a larger data set, but simulating the data led to this addressable, but challenging, ussue.

**Comment by restrellado** [comment]
I wonder if one solution is to generate a separate table of higher value `yvar1` and higher value `yvar2`. `yvar2` could be generated from `yvar1` * a coefficient + an error term (assuming you want a linear relationship). Once you have that then you can append this new dataset to the dataset you were using in the walkthrough. I can work up a reprex but just wanted to throw the idea out there in case you get to it before me.

**Comment by jrosen48** [comment]
That would be super helpful.

**Comment by restrellado** [comment]
[Here's what I was thinking about](https://github.com/restrellado/example_sim_data). I added you in as a collaborator so we can mess around with it more. I haven't had a chance to update my repo and run all your code yet so I don't know if this can get bolted on neatly to your simulated dataset, but the rough idea is there. We can make adjustments to the parameters so it's more plausible then transform it into the shape you want it. Once it's appended to your dataset, then you'll have this whole subset in there of higher and related `yvar1` and `yvar2` values. Am I on the right track?

**Comment by jrosen48** [comment]
Thanks all. The key that I am still challenged to address is that it is not *yvar1* and *yvar2* need to be correlated (i.e., within a person), but rather that **nominators with higher values of yvar2 need to have have relations with nominees with higher levels of yvar1**. Each nominator can report relations with, say, between 1 to 10 nominees (this is up to us).

**Comment by ivelasq** [comment]
Hi Josh, just fyi - when I run line 25 in Walkthrough 4, I get the error `no applicable method for 'select_' applied to an object of class "function"`

**Comment by restrellado** [comment]
@jrosen48 I think SNA is working now so I'm going to close this. Feel free to reopen if I got that wrong. Thanks y'all!
