### ISSUE TITLE
Missing references

### ISSUE THREAD

**Issue by ivelasq** [data-edu/data-science-in-education#415]
I think we're on the home stretch of the references... please see the missing ones here:

pandoc-citeproc: reference learningstatswithr not found
pandoc-citeproc: reference msdatause not found
pandoc-citeproc: reference msdatause not found
pandoc-citeproc: reference eccles1983 not found
pandoc-citeproc: reference R-tabulizer not found
pandoc-citeproc: reference R-rJava not found
pandoc-citeproc: reference bookparis2017culturally not found
pandoc-citeproc: reference bambric not found

**Comment by ivelasq** [comment]
@joshuarosenberg mind if I tag you on this?

**Comment by jrosen48** [comment]
thanks, on it

**Comment by ivelasq** [comment]
Well, bookdown is magical. Now some of these references show up but others don't... (I may have messed up something with git too....):

New errors:
pandoc-citeproc: reference learningstatswithr not found
pandoc-citeproc: reference msdatause not found
pandoc-citeproc: reference msdatause not found
pandoc-citeproc: reference eccles1983 not found
pandoc-citeproc: reference disaggregate not found
pandoc-citeproc: reference descriptive not found
pandoc-citeproc: reference frpl not found
pandoc-citeproc: reference urbanpov not found
pandoc-citeproc: reference dsieurproposal not found
pandoc-citeproc: reference bookparis2017culturally not found
pandoc-citeproc: reference bambric not found

**Comment by jrosen48** [comment]
Thanks - addressed in #470 - if we run again, will be curious about these first three, which are now showing up in one of the bibs

pandoc-citeproc: reference R-tabulizer not found -- in packages.bib - wondering what's up
pandoc-citeproc: reference R-rJava not found -- in packages.bib - wondering what's up
pandoc-citeproc: reference dsieurproposal not found - in book.bib - wondering whats up

pandoc-citeproc: reference learningstatswithr not found -- added
pandoc-citeproc: reference msdatause not found -- added
pandoc-citeproc: reference msdatause not found -- added (see above)
pandoc-citeproc: reference eccles1983 not found -- changed in c7 and added 
pandoc-citeproc: reference bookparis2017culturally not found - fixed citation in c16
pandoc-citeproc: reference bambric not found - added, sorry I missed this
pandoc-citeproc: reference disaggregate not found -- added
pandoc-citeproc: reference descriptive not found -- added
pandoc-citeproc: reference frpl not found -- added
pandoc-citeproc: reference urbanpov not found -- added
