### ISSUE TITLE
possible next steps for walkthrough 1

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#42]
Walkthrough 1 ([`06-walkthrough-1.Rmd`](https://github.com/data-edu/data-science-in-education/blob/master/06-walkthrough-1.Rmd)) has a foundation, but has some room for improvement, especially with respect to the newer parts on visualizations and models.

Right now, these focus on a fairly obvious relationship between the time students spent on the course and the percentage of possible points earned. There are other relationships that could be more interesting. A few ideas:

- Look at differences by the five subjects (anatomy and physiology, physics, biology, chemistry, and forensic science)
     - To do this analysis, the code for the subject would have to be identified from the course-ID; this would take a little regex work
- Look at some of the relations of the self-report variables for interest, value, and self-efficacy (perhaps with time spent on course)

We could also look at gender, though it's really sex, and I'm concerned about treating this variable as a token dichotomous/dummy code one in any case (but am open to feedback on this!).

**Comment by ivelasq** [comment]
Hi, I can add on to this walkthrough but when running the code, I get an error on line 136 because type must be double not integer. Does anybody else get this error?

**Comment by jrosen48** [comment]
Awesome. I think @restrellado is working on this in #46 (this morning!)

**Comment by restrellado** [comment]
Yep I'm on it!
