### ISSUE TITLE
loading the tidyverse is redundant when loading dataedu

### ISSUE THREAD

**Issue by kierisi** [data-edu/data-science-in-education#420]
the `tidyverse` is included as a dependency in `dataedu` - when we ask readers to load the `tidyverse` in a script where they're loading `dataedu` it's a redundant step.

if we move to put `dataedu` on CRAN we'll need to remove the `tidyverse` dependency, but I'm not sure if this is something we have the capacity to address prior to printing.

**Comment by ivelasq** [comment]
Tidyverse is not a dependency in dataedu - please see here: https://github.com/data-edu/dataedu/blob/master/DESCRIPTION. The tidyverse package is loaded with install_dataedu() though.
