### ISSUE TITLE
add functions introduced section to foundational skills and walkthrough sections

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#424]
This will involve using the following two Google Docs documents:

- Walkthrough Tracking
- foundational_programming_skills_tracker

**Comment by emilybovee** [comment]
Hey Josh, thanks for opening this. Let me know when you are going to work on this. I'm working on C5 today and likely C6 tomorrow/Tuesday

**Comment by jrosen48** [comment]
Yw! I can and hold off until later (Tues or later - will message you in Slack) - I am working on C10 today.

**Comment by jrosen48** [comment]
I am also thinking of adding a "Topics Covered", i.e.:

## Topics Covered

- Cleaning data
- Tidying data
- Exploring data
- Visualizing data

**Comment by jrosen48** [comment]
draft of this is in G-docs - hoping to add to the book today

**Comment by jrosen48** [comment]
will do this first thing tomorrow!

**Comment by jrosen48** [comment]
addressed in #507
