### ISSUE TITLE
In c9, show how to load the tabulizer-processed data in the walkthrough

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#431]
It should be joined data

**Comment by ivelasq** [comment]
Hey there! I went through, changed the {dataedu} data names to match, added info on how to use the package as well as data in the repo. Question for you: are you adding Functions Introduced? Right now there's only one there. 

0fbd054bea4f59dd80d559d2a019e52b5d7fb79c

**Comment by jrosen48** [comment]
Sweet to the beat. Yes, will add more - just started here and in c10 (#428). I think it will be a bit of work but will be useful (and helpful for indexing). Made an issue for this very ... issue here: #424

**Comment by ivelasq** [comment]
Hey there. I think (hope) I've resolved this. Let me know~

**Comment by jrosen48** [comment]
assigned to me to check tomorrow! am sure it's ready

**Comment by jrosen48** [comment]
looks good!
