### ISSUE TITLE
chapter 9: rJava installation on Windows 10 is (also) hellacious

### ISSUE THREAD

**Issue by kierisi** [data-edu/data-science-in-education#436]
The text mentions that installing rJava is tough on Macs, but [this](https://cimentadaj.github.io/blog/2018-05-25-installing-rjava-on-windows-10/installing-rjava-on-windows-10/) is the current process on Windows 10 - which I'd argue is pretty tough for someone not used to rooting around in their computer. I'd recommend making rJava optional for all platforms (although provide resources on accessing for the intrepid.)

**Comment by ivelasq** [comment]
removed reference that installation is difficult on Macs; added the PDF file output to {dataedu} and have them it in the chapter now
