### ISSUE TITLE
chapter 10: data download links go to raw files

### ISSUE THREAD

**Issue by kierisi** [data-edu/data-science-in-education#437]
the dataset links in chapter 10 go directly to raw files viewed in the browser, which cannot be downloaded. readers can still get the data into a .csv, but we'd need to provide more instruction on how to do that. 

it might be more helpful to point to the file within the repo, since there's a download button available: https://github.com/data-edu/data-science-in-education/blob/master/data/longitudinal_data/bchildcountandedenvironments2016.csv

**Comment by jrosen48** [comment]
I'm on this right now (over in #428)

**Comment by restrellado** [comment]
Addressed in #428.  Thanks @jrosen48!
