### ISSUE TITLE
Chapter 14/Walkthrough 8 Narrative Review

### ISSUE THREAD

**Issue by ivelasq** [data-edu/data-science-in-education#441]
Hey all,

Awesome chapter! Had a great time reading through!! What an awesome final walkthrough and send off into the exciting world of ML.

I have a few questions that need your content expertise/opinions...

**Narrative**
- Do we have a source on how online instruction is becoming more prevalent?
- The tense changes throughout the chapter, because this is based on a previous analysis. To match the rest of the chapters, I think we should use present tense. Want to make sure you agree.
- This uses the same dataset as Chapter 7 but is detailed much further here. (1) Thoughts on saying that in Chapter 7 (something like, more details on this dataset and methodology are in Chapter 14)? Or adding the more detailed methodology in an appendix? Especially considering that the methods section is much longer than the other walkthroughs. (2) Can we match the description of the data? For example, the list of four details on the dataset are slightly different between the two chapters.
- I do not understand this line:  We set this next code chunk up to not run here (if you are viewing the book online), as we will do this analysis with the variables' original values.
- I changed "the model is robust" to "the model is able to handle new data" - is that correct?
- We use the term 'parameter' and 'parameter space' a lot - are there good definitions for them? Happy to include but I just don't know enough...

**Data**
- A heads up that I changed data to df, as using data as an object name can create conflicts with other packages.
- In line 134, it says to filter semester != S217 variables but S217 isn't in the dataframe. Should I remove?
- I had set all the seeds to 2020 when I was trying to standardize them across the book programmatically. This changes the final results of df_test_augmented. What does it mean that both the RSME and the R squared went down...?

**Comment by emilybovee** [comment]
Good ideas. Sorry I missed these questions until now.

**Comment by emilybovee** [comment]
- Present tense sounds good. 

- That's a good question about the methodology detail level @jrosen48 what do you think?

- Regarding the confusing line: yeah, let's take that out. That little fiend was causing us all sorts of headaches.

-

**Comment by emilybovee** [comment]
Re: data

- For df vs. data: oh good, good to know, I do this a lot so I should adjust...

- For S217: weird, maybe that was an artifact of an old version of the dataset?

- For the values changing, hopefully we fixed that...

**Comment by emilybovee** [comment]
For tense: I think that the actual walk-through steps are in the right tense, but the sentences describing the study context are in past tense. Are we okay with that? I tend to think that describing the research study from the past in the present tense would feel awkward. CC @ivelasq

**Comment by emilybovee** [comment]
Fixed w pr #495
