### ISSUE TITLE
chapter 9: data needs to be added to dataedu package

### ISSUE THREAD

**Issue by kierisi** [data-edu/data-science-in-education#444]
the following code is offered as an option for accessing data, however the corresponding dataset is not (yet) in the package:

```
race_pdf <-
  dataedu::race_pdf
```

**Comment by ivelasq** [comment]
It is available in the package. Uploaded 3/29, you may need to reinstall the package to see it on your end: https://github.com/data-edu/dataedu/tree/master/data
