### ISSUE TITLE
chapter 9: provide information on file structure

### ISSUE THREAD

**Issue by kierisi** [data-edu/data-science-in-education#446]
the following code assumes that the reader has the same file structure as the chapter author:

```
race_pdf <-
  readRDS(here("data", "agg_data", "race_pdf.Rds"))
```

it would be helpful to include a sentence either prior to the code chunk or within the code chunk explaining how this function works, and how the reader can _also_ get it to work on their home machine (that they'll need to create directories//folders).

**Comment by ivelasq** [comment]
Fixed in #468. Thanks!
