### ISSUE TITLE
chapter 10: object Year not found

### ISSUE THREAD

**Issue by kierisi** [data-edu/data-science-in-education#452]
I'm not sure how to troubleshoot this one - `Year` is very clearly in the dataset, but I'm getting the error message: `Error in .f(.x[[i]], ...) : object 'Year' not found `

Code:
```
pick_vars <-
  function(df) {
    df %>%
      select(Year) %>% 
      select_at(vars(
        contains("State", ignore.case = FALSE),
        contains("SEA", ignore.case = FALSE),
        contains("male")
      ))
  }

# use the function with `all_files`
all_files <-
  all_files %>%
  map(pick_vars)
```

**Comment by restrellado** [comment]
We can still reproduce the problem by downloading the CSVs using a Windows machine. Still working on this one

**Comment by restrellado** [comment]
More research on this: 

When I download on my Mac using code like this for each dataset: 

```
download.file(
  # the url argument takes a URL for a CSV file
  url = 'https://bit.ly/3dCtVtf',
  # destfile specifies where the file should be saved
  destfile = "~/Desktop/bchildcountandedenvironments2012.csv")
```

The files download as expected. Each year of data has 4 extra lines on top except for 2016, which has 3 extra lines on top. 

When we download to a Windows machine using the same script, there are extra lines at the top of each dataset. This causes the cleaning script in this chapter to work incorrectly and no column is assigned to `Year`.

**Comment by restrellado** [comment]
Thank you to [Ellis](https://twitter.com/ellis_hughes) for this solution!
