### ISSUE TITLE
Chapter 14: Should we specify packages to load?

### ISSUE THREAD

**Issue by emilybovee** [data-edu/data-science-in-education#455]
When running the code clean, realized that there are not library calls. I thought it would be good to specify which packages to load in case they are running this chapter in its own file.
Packages used, in order:
-dataedu
-tidyverse
-tidylog
- caret

**Comment by emilybovee** [comment]
additional pkgs
e1071
ranger

**Comment by jrosen48** [comment]
agree - @ivelasq were these perchance removed in the course of getting this chapter to render? j/w.

**Comment by ivelasq** [comment]
I don't know why they're missing - if I deleted them, sorry, I didn't mean to! I'm baffled that the book was able to render without them too...

**Comment by emilybovee** [comment]
I think this was probably me leaving them out and wasn't trying to point fingers at anyone! Happy to fix this later.

**Comment by ivelasq** [comment]
Oh! I think it's because `echo = FALSE` for the chunk! Ghost library calls.

**Comment by emilybovee** [comment]
You figured it out!! Thanks!!!! I guess we change it to echo = TRUE. lol

**Comment by emilybovee** [comment]
fixed
