### ISSUE TITLE
chapter 11: package installation mid-chapter

### ISSUE THREAD

**Issue by kierisi** [data-edu/data-science-in-education#459]
in the middle of the chapter we ask the reader to install `install.packages("textdata")` but then never load it using `library()` - it would be helpful to include an explanation as to why we don't need to do that (I'm not clear what it is, because I don't see any namespacing!) because this is inconsistent with what we talk about in other chapters.

**Comment by restrellado** [comment]
I looked into this. You need the {textdata} package installed for `tidytext::get_sentiments("nrc")` to work correctly. I uninstalled {textdata} and ran `get_sentiments("nrc")`, which returned 

```Error: The textdata package is required to download the NRC word-emotion association lexicon. Install the textdata package to access this dataset.``` 

I installed {textdata} again and verified that you don't need to load it with `library(textdata)`, just need to have it installed. 

I'll add some narrative to explain this a little better.
