### ISSUE TITLE
chapter 12//book thoughts: installation prior to loading

### ISSUE THREAD

**Issue by kierisi** [data-edu/data-science-in-education#460]
we have an inconsistent pattern in the book where we'll ask users to install packages before loading them (example: chapter 11), or we'll simply load the packages without mentioning that they may need to be installed (example: chapter 12)

it would be nice to have a consistent system for this so that readers who "choose their own adventure" in the text have the same experience between walkthroughs.

**Comment by jrosen48** [comment]
can work on this too - will plan to mention that they may need to be installed in every case

**Comment by jrosen48** [comment]
added descriptions to each of the chapters -- reminding readers (after the first walkthrough, where I included slightly more specific instructions) to install packages via `install.packages()` and referring back to the packages section fo the foundational skills chapter for an overview and description of how to do this, if needed.
