### ISSUE TITLE
chapter 12: dataframe not found

### ISSUE THREAD

**Issue by kierisi** [data-edu/data-science-in-education#462]
at the end of the chapter this chunk of code returns the error: `Error in is.data.frame(data) : object 'edgelist1' not found`

```
m_selection <- 
  glm(relate ~ 1 + same, data = edgelist1)
```

is there supposed to be an edgelist1? or is the `1` a typo?

**Comment by jrosen48** [comment]
will check this. wonder if this was supposed to be eval = FALSE

**Comment by jrosen48** [comment]
first thing tomorrow am

**Comment by jrosen48** [comment]
added this parenthetical statement to the description of why this code is included (and moved it to the appendix, where it belonged!): "(which is not run, but is included as an example of the code for this kind of selection model)"
