### ISSUE TITLE
chapter 13: error in bookdown render?

### ISSUE THREAD

**Issue by kierisi** [data-edu/data-science-in-education#463]
when I run the following code I get this error: `Warning message:
In model.matrix.default(~x - 1, model.frame(~x - 1), contrasts = FALSE) :
  non-list contrasts argument ignored`
```
dummies::dummy(iris$Species) %>%
  head()
```
and my output is:
![dummies_output](https://user-images.githubusercontent.com/23085445/78316629-c0605580-7525-11ea-8f8f-7b6612663165.png)

while the book is showing:
![book_render](https://user-images.githubusercontent.com/23085445/78316693-eb4aa980-7525-11ea-8b9e-8a4209a48414.png)

**Comment by ivelasq** [comment]
Fixed in #490. Used this as reference: https://stackoverflow.com/questions/47976971/r-dummies-package-weird-column-names-when-knitted-via-rmd

Thanks!
