### ISSUE TITLE
chapter 13: package installation comes after package loading

### ISSUE THREAD

**Issue by kierisi** [data-edu/data-science-in-education#466]
at the start of the chapter we ask the reader to load {lme4}, but then at the end of the chapter we ask them to install {lme4}. I would recommend moving the installation to above the code chunk with `library()`

**Comment by kierisi** [comment]
the same is true for the {performance} package

**Comment by jrosen48** [comment]
will address (and move)

**Comment by jrosen48** [comment]
added descriptions to each of the chapters -- reminding readers (after the first walkthrough, where I included slightly more specific instructions) to install packages via `install.packages()` and referring back to the packages section fo the foundational skills chapter for an overview and description of how to do this, if needed.
