### ISSUE TITLE
7.11 Interpretation of regression model results

### ISSUE THREAD

**Issue by jimmyvluong** [data-edu/data-science-in-education#551]
Hi,

I'm working through the first walkthrough and noticed that in the final section,
"...FrSc—forensic science—and Ocn—oceanography..." are associated with a higher final grade. Shouldn't the two subjects associated with a higher final grade be "forensic science" and "physics"?

Jimmy

**Comment by ivelasq** [comment]
Hi Jimmy! Yes, you are correct. This is fixed in the print version of the book but we'll fix it in the bookdown! Thank you so much - I'll close this thread once we fix this error!

**Comment by ivelasq** [comment]
Fixed in #552! Thanks again, Jimmy!
