### ISSUE TITLE
Switch from travis to GitHub Actions?

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#558]
https://ropenscilabs.github.io/actions_sandbox/

I followed the above instructions for another project - it worked relatively painlessly! Travis is shutting down free accounts (I think/mostly) within a few weeks.

**Comment by ivelasq** [comment]
Ooh thanks Josh, I also know that we are supposed to do this because Travis is unsafe, as well. Did you have to do anything to remove Travis?

**Comment by ivelasq** [comment]
Completed via https://github.com/data-edu/data-science-in-education/commit/ac1247a74e929a5228a6ab14ddb8b3c90bcbde81 :)
