### ISSUE TITLE
Walkthrough 2 - typos

### ISSUE THREAD

**Issue by morganlig** [data-edu/data-science-in-education#564]
Typo at the very end - 

> (PDF, Word, HTML, and other formats format).

And the comment in the code chunk should not be "Scatterplot" -

> {r fig8-2, message = FALSE, warning = FALSE, results = 'hide', fig.cap = "Distribution of Classwork Scores", fig.showtext = TRUE}
> #Scatterplot of continuous variable
> classwork_df %>%
>   ggplot(aes(x = classwork_number,
>              y = score,
>              fill = classwork_number)) +
>   geom_boxplot() +
>   labs(title = "Distribution of Classwork Scores",
>        x = "Classwork",
>        y = "Scores") +
>   scale_fill_dataedu() +
>   theme_dataedu() +
>   theme(
>     # removes legend
>     legend.position = "none",
>     # angles the x axis labels
>     axis.text.x = element_text(angle = 45, hjust = 1)
>     )

**Comment by ivelasq** [comment]
Thanks @morganlig !
