### ISSUE TITLE
error in random forest chapter: missing package

### ISSUE THREAD

**Issue by jmostipak** [data-edu/data-science-in-education#62]
in compiling for `bookdown` the following error is showing up for chunks on lines:

- 171-175
- 185-195
- 201-211
- 278-285
- 320-332

```
Error: Required package is missing
```
I've set the code chunk to `error = TRUE` in order to facilitate rendering the text, but these will need to be addressed.

**Comment by jrosen48** [comment]
will take a peak at this

**Comment by restrellado** [comment]
Hey y'all it says walkthrough 8 but I'm assuming it's chapter 8. That would be Walkthrough 3: Random forest on survey data. Let me know if I got that wrong!

**Comment by ivelasq** [comment]
The error I get is: `Error in `[.data.frame`(data, , "pred") : undefined columns selected` (when running `defaultSummary(as.data.frame(d_train)` on line 198)

**Comment by emilybovee** [comment]
I will work on this

**Comment by jrosen48** [comment]
I think that all of the code in the RF chapter is now running (and that we can close this issue!)
