### ISSUE TITLE
simulate data based on online science classes data

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#73]
The online science classes data set (used in [walkthrough 1](https://github.com/data-edu/data-science-in-education/blob/master/06-walkthrough-1.Rmd) and [walkthrough 3](https://github.com/data-edu/data-science-in-education/blob/master/08-walkthrough-3.Rmd) is anonymous but is actual data I collected with a colleague (a post-doc) at MSU. 

I think it would be preferable to simulate data based upon this data - instead of sharing it directly.

**Comment by jrosen48** [comment]
this package, simPop, may be helpful: https://cran.r-project.org/web/packages/simPop/index.html

> Tools and methods to simulate populations for surveys based on auxiliary data. The tools include model-based methods, calibration and combinatorial optimization algorithms. The package was developed with support of the International Household Survey Network, DFID Trust Fund TF011722 and funds from the World bank.

**Comment by restrellado** [comment]
@jrosen48 Is this one we're still working on or should we close it?

**Comment by restrellado** [comment]
Closing this one for now, but feel free to reopen it if it's still something we need to take care of

**Comment by jrosen48** [comment]
Still need to do this to be able to share this publicly (so should have been done earlier). Sorry I didn't think of this one. Will try to do.

**Comment by jrosen48** [comment]
this is, gloriously, done!
