### ISSUE TITLE
chapter on Bayesian methods?

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#74]
From my friend [@markubsch](https://twitter.com/markubsch) via Twitter:

> I recently looked at the GitHub page for your data science book. Have you though of having a chapter on bayesian methods as well? I think there are some arguments that make Bayes especially interesting in education.

**Comment by ivelasq** [comment]
How much leeway do we have to add chapters now?

**Comment by jrosen48** [comment]
Yeah, I think that's the right question. I'm not sure; my sense is that we have *some* leeway, especially if we have a strong rationale. Thinking this is a cool idea but that it may be slightly advanced. Thoughts?

**Comment by restrellado** [comment]
Hey y'all just checking in on this. We'll leave it up awhile longer in case anyone has strong feelings about it. If not, we can close this thread and revisit if needed

**Comment by cjvanlissa** [comment]
I could write a chapter on Bayesian informative hypothesis testing using fractional approximate Bayes factors (the `bain` package)?

**Comment by restrellado** [comment]
Hi @cjvanlissa ! Thank you so much for offering. Right now there aren't plans for a chapter on this, but we'll let you know if anything changes. Thanks again for reaching out!
