### ISSUE TITLE
addition of work works with data content

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#79]
From Slack:

> wonder if we could explicitly discuss who works with data and how they do so (maybe in the intro.), i.e. what types of data do administrators OR data analysts OR researchers primarily work with. And maybe we can suggest specific chapters that will be particularly relevant. Part of this could be delimiting who works with data but who is not a focus of our audience (i.e., parents, and, to a lesser extent cuz we touch on this, teachers and students)

> Maybe this can be in chapter 2 under “pick a chapter that’s useful for you”?

**Comment by restrellado** [comment]
Oh this is really good–sorry I missed it! I'll work on this one

**Comment by restrellado** [comment]
I'm going to try writing about this by pointing at themes in the walkthroughs: 

 - Student perception of learning: multi-level models on survey data, text analysis of tidytuesday tweets 
 - Student performance: gradebook analysis and random forest on final course grades . 
 - Getting value from public data: working with aggregate data, longitudinal analysis on special ed data
