### ISSUE TITLE
synthesize data set for random forest chapter

### ISSUE THREAD

**Issue by jrosen48** [data-edu/data-science-in-education#96]
- Review the file for chapter 8 (`08-walkthrough-3.Rmd`) to see which variables are included - in any way at all - in the analysis
- Record what those variables are
- Subset the online science motivation dataset, used in that walkthrough and stored in `data/online-science-motivation/processed/online-science-motivation.csv`, to include only those variables used in the analysis
- Use `synthpop::syn()` on the subset data frame to synthesize a new data frame
- Replace the online science motivation dataset with the new, synthesized dataset

**Comment by emilybovee** [comment]
@jrosen48  I'm working on finalizing this chapter today/maybe into tomorrow. Are we ok keeping the dataset as-is or is there a problem?

**Comment by jrosen48** [comment]
acknowledging I saw this (and am thinking on this!!!)

**Comment by jrosen48** [comment]
the data you added to the package worked brilliantly for me. 

I am working on this, as I think that it is preferable for the online science motivation dataset data to be "synthesized" versions of the data - versions that maintain the relationships in the original data, but are simulated (for privacy-related reasons, even though the data will be anonymous).

**Comment by emilybovee** [comment]
Sounds good, @jrosen48 , thanks! cross-referencing this with the issue in the `dataedu` package, am I understanding correctly that the sci_mo_data dataset will now read your new, synthesized data? so - I don't need to change the data reading code in the ML walkthrough ?

**Comment by jrosen48** [comment]
confirming we discussed this in Slack @emilybovee - this should be good to go
